# - name: 安装openstack服务基础软件包
#   shell: add-apt-repository cloud-archive:stein

# - name: 更新软件包
#   shell: apt update && apt dist-upgrade

- name: 安装软件包python-openstackclient
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - python3-openstackclient
      - expect 
- name: controller节点安装数据库服务
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - mariadb-server
      - python3-pymysql
  when: (ansible_hostname == "controller")

- name: controller节点配置创建数据库配置文件mariadb_openstack.cnf
  template:
    src: mariadb_openstack.cnf
    dest: /etc/mysql/mariadb.conf.d/mariadb_openstack.cnf
  when: (ansible_hostname == "controller")
  
- name: controller启动mariadb服务
  systemd:
    name: mariadb
    state: started
    enabled: yes
  when: (ansible_hostname == "controller")
  
- name: controller节点设置mairadb密码
  script:
    cmd: /etc/ansible/openstack/roles/prepare/files/mysql_secure_installation.sh
  when: (ansible_hostname == "controller")

- name: 创建各组件用户以及对应的数据库
  script:
    cmd: /etc/ansible/openstack/roles/prepare/files/create_database.sh
  when: (ansible_hostname == "controller")
