#- name: controller 修改配置文件/etc/apache2/httpd.conf
  #shell: sed -i 's/#ServerName www.example.com:80/ServerName controller/g' /etc/apache2/apache2.conf
- name: controller 修改配置文件/etc/apache2/apache2.conf
  copy:
    src: apache2.conf
    dest: /etc/apache2/apache2.conf

- name: controller 创建符号链接文件
  command: ln -s /usr/share/keystone/wsgi-keystone.conf /etc/apache2/

- name: controller 启动Apache服务
  systemd:
    name: apache2
    state: started
    enabled: yes
