- name: controller 安装nova和placement服务组件
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - nova-api
      - nova-conductor
      - nova-novncproxy
      - nova-scheduler
      - placement-api
  when: (ansible_hostname == "controller")

- name: controller 修改配置文件/etc/nova/nova.conf
  template:
    src: controller_nova.conf
    dest: /etc/nova/nova.conf
    owner: root
    group: nova
    mode: '0640'
  when: (ansible_hostname == "controller")

- name: controller 修改配置文件/etc/apache2/sites-available/00-nova-placement-api.conf
  copy:
    src: controller_00-nova-placement-api.conf
    dest: /etc/apache2/sites-available/00-nova-placement-api.conf
    owner: root
    group: root
    mode: '0640'
  when: (ansible_hostname == "controller")

- name: controller 重启httpd服务
  systemd:
    name: apache2
    state: started
  when: (ansible_hostname == "controller")

- name: controller 同步数据库01
  shell: su -s /bin/sh -c "nova-manage api_db sync" nova
  when: (ansible_hostname == "controller")
  
- name: controller 同步数据库02
  shell: su -s /bin/sh -c "nova-manage cell_v2 map_cell0" nova
  when: (ansible_hostname == "controller")
  
- name: controller 同步数据库03
  shell: su -s /bin/sh -c "nova-manage cell_v2 create_cell --name=cell1 --verbose" nova
  when: (ansible_hostname == "controller")
  
- name: controller 同步数据库04
  shell: su -s /bin/sh -c "nova-manage db sync" nova
  when: (ansible_hostname == "controller")
  
- name: controller 启动nova相关服务
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - nova-api
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy
  when: (ansible_hostname == "controller")
