- name: controller 创建glance用户、角色、服务实体
  script: /etc/ansible/openstack/roles/glance/files/glance_project_user_role_api.sh
  environment:
    OS_USERNAME: admin
    OS_PASSWORD: 123456
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: Default
    OS_PROJECT_DOMAIN_NAME: Default
    OS_AUTH_URL: http://controller:5000/v3
    OS_IDENTITY_API_VERSION: 3

- name: controller 安装镜像服务软件
  apt:
    name: glance

- name: controller 修改配置文件/etc/glance/glance-api.conf
  copy:
    src: glance-api.conf
    dest: /etc/glance/glance-api.conf
    owner: root
    group: glance
    mode: '0640'

- name: controller 修改配置文件/etc/glance/glance-registry.conf
  copy:
    src: glance-registry.conf
    dest: /etc/glance/glance-registry.conf
    owner: root
    group: glance
    mode: '0640'

- name: controller 同步数据库
  shell: su -s /bin/sh -c "glance-manage db_sync" glance
#  register: get_glance
  
#- name: controller 显示同步信息
#  debug: msg={{ get_glance.stdout_lines }}
  
- name: controller 启动glance-api.service服务
  systemd:
    name: glance-api
    state: restarted
    enabled: yes

# 此服务已被弃用
#- name: controller 启动glance-registry.service服务
#  systemd:
#    name: glance-registry
#    state: started
#    enabled: yes
#

#- name: controller 下载镜像
#  shell: wget http://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img -P ~/

#- name: controller 导入镜像
#  shell: openstack image create "cirros" --file ~/cirros-0.4.0-x86_64-disk.img --disk-format qcow2 --container-format bare --visibility=public
